# Generated by Django 5.0.6 on 2024-10-25 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobicrowd', '0002_remove_patient_gender_event_comment_eventpatient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobicrowd.patient'),
        ),
    ]
