# Generated by Django 5.0.6 on 2024-10-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobicrowd', '0003_alter_comment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='availability',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualifications',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
