# Generated by Django 5.0.6 on 2024-10-26 22:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobicrowd', '0003_assessment_anxiety_rating_assessment_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='recommendations',
            field=models.TextField(blank=True, help_text='Recommendations for further action or therapy based on results.'),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='reflections',
            field=models.TextField(blank=True, help_text="Patient's reflections or thoughts after the assessment."),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='comments',
            field=models.TextField(blank=True, help_text='Additional comments or notes about your assessment.'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='coping_mechanisms',
            field=models.TextField(blank=True, default='No coping mechanisms reported.', help_text='Describe any coping strategies you use to manage stress and anxiety.'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='date_of_assessment',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of the assessment.'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='description',
            field=models.TextField(help_text='Brief description of the assessment purpose.'),
        ),
    ]
