# Generated by Django 5.0.6 on 2024-10-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobicrowd', '0004_alter_doctor_approved_alter_doctor_availability_and_more'),
        ('mobicrowd', '0004_assessmentresult_recommendations_and_more'),
    ]

    operations = [
    ]
