# Generated by Django 5.0.6 on 2024-10-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobicrowd', '0005_merge_20241027_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='title',
        ),
        migrations.AddField(
            model_name='assessment',
            name='daily_highlights',
            field=models.TextField(blank=True, help_text='List any positive experiences or highlights from today.'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='energy_level_rating',
            field=models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Neutral'), (4, 'High'), (5, 'Very High')], default=3, help_text='Rate your energy level on a scale from 1 (Very Low) to 5 (Very High).'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='gratitude_entries',
            field=models.TextField(blank=True, help_text='List things you are grateful for today.'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='physical_pain_rating',
            field=models.IntegerField(choices=[(1, 'None'), (2, 'Mild'), (3, 'Moderate'), (4, 'Severe'), (5, 'Extreme')], default=1, help_text='Rate your physical pain level today on a scale from 1 (None) to 5 (Extreme).'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='productivity_rating',
            field=models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')], default=3, help_text='Rate your productivity level today on a scale from 1 (Very Low) to 5 (Very High).'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='sleep_quality_rating',
            field=models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Fair'), (4, 'Good'), (5, 'Excellent')], default=3, help_text='Rate the quality of your sleep on a scale from 1 (Very Poor) to 5 (Excellent).'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='social_interactions_rating',
            field=models.IntegerField(choices=[(1, 'None'), (2, 'Very Few'), (3, 'Some'), (4, 'Many'), (5, 'Very Many')], default=3, help_text='Rate your social interactions today on a scale from 1 (None) to 5 (Very Many).'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='substance_use',
            field=models.BooleanField(default=False, help_text='Indicate if you have used any substances (alcohol, drugs, etc.) today.'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='thought_patterns',
            field=models.TextField(blank=True, default='No specific thoughts reported.', help_text='Describe any persistent thoughts or patterns (negative or positive) you experienced today.'),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='Any additional notes or remarks about the assessment results.'),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='flagged_for_follow_up',
            field=models.BooleanField(default=False, help_text='Indicate if this result is flagged for a mandatory follow-up.'),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='review_date',
            field=models.DateField(blank=True, help_text='Date when the assessment results were reviewed.', null=True),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='reviewed_by',
            field=models.CharField(blank=True, help_text='Name of the reviewer or therapist who reviewed the assessment results.', max_length=100),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='urgency_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', help_text='Indicate the urgency level based on the assessment results.', max_length=10),
        ),
    ]
