# Generated by Django 5.0.6 on 2024-10-27 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobicrowd', '0006_remove_assessment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='energy_level_rating',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='follow_up_needed',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='productivity_rating',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='social_interactions_rating',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='substance_use',
        ),
    ]
